#!/usr/bin/env bash

lab_directory=/home/jonas/Github/puppet-lab

cd "$lab_directory"

tar -cf code.tar code
lxc file push code.tar puppetmaster/etc/puppetlabs/code.tar
lxc exec puppetmaster -- sh -c "rm -rf /etc/puppetlabs/code"
lxc exec puppetmaster -- sh -c "tar -xf /etc/puppetlabs/code.tar -C /etc/puppetlabs"
rm -f code.tar

